# -*- coding: utf-8 -*-
"""password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WcvFll6NaDkUewBLdli3zy4R0rjkRlq9
"""

import random # ランダム選択
import string # 文字セット定義

LOWERCASE = string.ascii_lowercase # a-z
UPPERCASE = string.ascii_uppercase # A-Z
DIGITS = string.digits             # 0-9
SYMBOLS = string.punctuation       # !@#$%&*...
ALL_CHARS = [LOWERCASE, UPPERCASE, DIGITS, SYMBOLS] # リストにまとめる

# パスワードを生成
def generate_password(length):

  REQUIRED_SETS = [LOWERCASE, UPPERCASE, DIGITS, SYMBOLS] # 必須文字列セット
  char_pool = LOWERCASE + UPPERCASE + DIGITS + SYMBOLS # 全ての文字種を含める

  if length < len(REQUIRED_SETS):
    return "エラー: 安全のため、パスワードの長さは4文字以上にしてください。"

  password = []

  for char_set in REQUIRED_SETS: # 4種類含ませる
    required_char = random.choice(char_set)
    password.append(required_char)

  remaining_length = length - len(REQUIRED_SETS) # 残りの長さ

  for _ in range(remaining_length): # 残り枠を埋める
    filler_char = random.choice(char_pool)
    password.append(filler_char)

  random.shuffle(password) # シャッフル
  return "".join(password) # リスト要素をデリミタで結合

# メインメニュー
def main():

  print("==================================")
  print("  シンプルなパスワード生成ツール")
  print("==================================")

  while True:
    try:
      length_input = input("パスワードの長さを入力してください (最低4文字、0で終了):")

      if length_input == '0':
        print("👋 ツールを終了します。")
        break

      length = int(length_input)

      if length < 4:
        print("⚠️ 長さは最低4文字（必須文字種数）で入力してください。")
        print() # 空行
        continue

      password = generate_password(length) # パスワード生成

      print("-" * 34)
      print(f"✅ 生成されたパスワード ({length}文字): {password}")
      print("-" * 34)
      print() # 空行


    except ValueError:
      print("⚠️ 無効な入力です。整数を入力してください。")
      print() # 空行
    except Exception as e:
      print(f"⚠️ 予期せぬエラーが発生しました: {e}")
      print() # 空行

# エントリーポイント
if __name__ == "__main__":
  main()

